# Generated by Django 4.0 on 2023-09-20 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_customer_rol_delete_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='Descripcion'),
        ),
    ]
